### PR TITLE
Antimony error handling

### PR DESCRIPTION
**Pull request by JonahRileyHuggins**
I went through the [API documentation for Antimony located here](https://antimony.sourceforge.net/antimony__api_8h.html#afb09af2a608c763a8606f3b5a607710b:~:text=LIB_EXTERN%20char*-,getLastError,),-When%20any%20function) to add in better error handling messages when antimony fails to load or compile a model. I've tested that the command, 'getLastError()' works as anticipated.

### CODE REVIEW

**Comment by ChocolateCharlie** [comment]
That's super interesting! I feel we cannot merge it as is though:

- The only file that should be changed is `create_model.py`, right? Some of your work on benchmark got included in the pull request, I believe that's a mistake.
- What's the advantage compared to printing the Python exception message? Actually, I was also thinking of eventually improve the exception handling because what we currently do is extremely basic.

**Comment by ChocolateCharlie** [comment]
This is [an example ](https://github.com/SPARCED/SPARCED/blob/exception_handling/SPARCED/src/compilation/create_model.py)of basic improvement of exception handling. Let me know if that could help too and if it makes any difference with Antimony's `getLastError() `function.

**Review by JonahRileyHuggins — COMMENTED** [review]
Files modifying the benchmarks directory have been removed. The only changes that should take affect should be the create_model.py. 

all files deleted exist in benchmark_adjustments branch, which is nearing completion.

**Review by ChocolateCharlie — APPROVED** [review]
LGTM

**Pull request merged**
